/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelos.Alumno;
import modelos.Carrera;
import modelos.Materia;

/**
 *
 * @author 50578
 */
public class FrmNt extends javax.swing.JFrame {
    ArrayList<Materia> asignatura = new ArrayList();
    Alumno alumno = new Alumno();
    DefaultListModel LstModelo = new DefaultListModel();
    DefaultListModel LstModelo2 = new DefaultListModel();
    DefaultListModel LstModelo3 = new DefaultListModel();

    /**
     * Creates new form FrmNt
     */
    public FrmNt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaNombreAlum = new javax.swing.JTextArea();
        LblCarrera = new javax.swing.JLabel();
        CmbUni = new javax.swing.JComboBox<>();
        CmbCarrera = new javax.swing.JComboBox<>();
        TxtCedula = new javax.swing.JTextField();
        LblCedula = new javax.swing.JLabel();
        ChkBxMasculino = new javax.swing.JCheckBox();
        ChkBxFem = new javax.swing.JCheckBox();
        ChkBxOtro = new javax.swing.JCheckBox();
        LblSexo = new javax.swing.JLabel();
        LblNombreAlum = new javax.swing.JLabel();
        LblUni = new javax.swing.JLabel();
        LblMstMatEv1 = new javax.swing.JLabel();
        LblMstNtCrt1 = new javax.swing.JLabel();
        LblMstNtQnt1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LstMatEvl = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        LstNtCrtAn = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        LstQntAn = new javax.swing.JList<>();
        TxtTeologia = new javax.swing.JTextField();
        LblTolg1 = new javax.swing.JLabel();
        LblDesBD1 = new javax.swing.JLabel();
        TxtDBD = new javax.swing.JTextField();
        LblTIC1 = new javax.swing.JLabel();
        TxtTIC = new javax.swing.JTextField();
        LblPOO1 = new javax.swing.JLabel();
        TxtPOO = new javax.swing.JTextField();
        LblCalDos1 = new javax.swing.JLabel();
        TxtCalDos = new javax.swing.JTextField();
        TxtCalUno = new javax.swing.JTextField();
        LblCalUno1 = new javax.swing.JLabel();
        LblNotasCrtAno2 = new javax.swing.JLabel();
        LblNotasQntAno1 = new javax.swing.JLabel();
        BtnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtAreaNombreAlum.setColumns(20);
        TxtAreaNombreAlum.setRows(5);
        jScrollPane1.setViewportView(TxtAreaNombreAlum);

        LblCarrera.setText("Carrera");

        CmbUni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UCA", "UAM", "UNI" }));

        CmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería Civil", "Ingeniería Industrial", "Ingeniería en Sistemas" }));

        LblCedula.setText("Cédula:");

        ChkBxMasculino.setText("Masculino");
        ChkBxMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBxMasculinoActionPerformed(evt);
            }
        });

        ChkBxFem.setText("Femenino");

        ChkBxOtro.setText("Otro");

        LblSexo.setText("Sexo:");

        LblNombreAlum.setText("Nombre del alumno:");

        LblUni.setText("Universidad");

        LblMstMatEv1.setText("Materias:");

        LblMstNtCrt1.setText("Cuarto Año:");

        LblMstNtQnt1.setText("Quinto Año:");

        jScrollPane3.setViewportView(LstMatEvl);

        jScrollPane8.setViewportView(LstNtCrtAn);

        jScrollPane7.setViewportView(LstQntAn);

        LblTolg1.setText("Teología:");

        LblDesBD1.setText("Desarrollo BD:");

        LblTIC1.setText("TIC:");

        TxtTIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTICActionPerformed(evt);
            }
        });

        LblPOO1.setText("POO:");

        LblCalDos1.setText("Cálculo 2:");

        LblCalUno1.setText("Cálculo 1:");

        LblNotasCrtAno2.setText("Notas Cuarto año:");

        LblNotasQntAno1.setText("Notas Quinto año:");

        BtnRegistro.setText("Registro");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblNotasCrtAno2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblCalUno1)
                                    .addComponent(LblTIC1)
                                    .addComponent(LblTolg1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTeologia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtTIC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCalUno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblDesBD1)
                                            .addComponent(LblPOO1)
                                            .addComponent(LblCalDos1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtCalDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtPOO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtDBD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblNotasQntAno1)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ChkBxMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ChkBxFem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ChkBxOtro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblUni)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CmbUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblCarrera)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblCedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtCedula))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblNombreAlum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblMstMatEv1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblMstNtCrt1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(BtnRegistro)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblMstNtQnt1))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCarrera)
                    .addComponent(CmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblUni))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkBxMasculino)
                    .addComponent(ChkBxFem)
                    .addComponent(ChkBxOtro)
                    .addComponent(LblSexo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNombreAlum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNotasCrtAno2)
                    .addComponent(LblNotasQntAno1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCalUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCalUno1)
                    .addComponent(LblCalDos1)
                    .addComponent(TxtCalDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPOO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTIC1)
                    .addComponent(LblPOO1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTeologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTolg1)
                    .addComponent(LblDesBD1)
                    .addComponent(TxtDBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMstMatEv1)
                    .addComponent(LblMstNtCrt1)
                    .addComponent(LblMstNtQnt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRegistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChkBxMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBxMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkBxMasculinoActionPerformed

    private void TxtTICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTICActionPerformed

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        // TODO add your handling code here:
        Alumno alumno = new Alumno();
        String seleccion = "";
        if (ChkBxMasculino.isSelected() && ChkBxFem.isSelected() && ChkBxOtro.isSelected()){
            seleccion+="-";
            JOptionPane.showMessageDialog(null, "Seleccione solamente un sexo");
        }else if(ChkBxMasculino.isSelected()){
            seleccion+="Masculino";
        }else if (ChkBxFem.isSelected()){
            seleccion+="Femenino";
        } else if (ChkBxOtro.isSelected()){
            seleccion+="Otro";
        } else if (ChkBxOtro.isSelected() && ChkBxMasculino.isSelected()){
            seleccion+="Seleccione solamente un sexo";
        } else if (ChkBxOtro.isSelected() && ChkBxFem.isSelected()){
            seleccion+="Seleccione solamente un sexo";
        } else if (ChkBxMasculino.isSelected() && ChkBxFem.isSelected()){
            seleccion+="Seleccione solamente un sexo";
        }else{
            seleccion+="-";
            JOptionPane.showMessageDialog(null, "No ha seleccionado su sexo");
        }
        //Creacion de objeto ESTUDIANTE
        alumno.setNombre(this.TxtAreaNombreAlum.getText());
        alumno.setSexo(seleccion);
        alumno.setCedula(this.TxtCedula.getText());
        //Creacion de objeto CARRERA
        Carrera matricula = new Carrera();
        matricula.setNombre(CmbCarrera.getSelectedItem().toString());
        matricula.setFacultad(CmbUni.getSelectedItem().toString());
        //CREACION DE ARREGLO PARA EL OBJETO CARRERA
        ArrayList<String> semestre = new ArrayList();
        semestre.add("Taller de Lectura");
        semestre.add("Taller de Redacción");
        semestre.add("Desarrollo Sostenible y Medio Ambiente");
        matricula.setPrimerSemestre(semestre);
        LstModelo.clear();
        LstModelo.addElement(semestre);
        this.LstMatEvl.setModel(LstModelo);
        //AGREGANDO LOS DATOS DE LA CARRERA AL ESTUDIANTE
        alumno.setNombreCarrera(matricula);
        //CREANDO EL ARREGLO DE LAS NOTAS DE 4TO AÑO DEL ESTUDIANTE
        ArrayList<Materia> cuarto = new ArrayList();
        Materia calculouno = new Materia();
        calculouno.setNombre("Cálculo 1");
        calculouno.setNota(Integer.parseInt(this.TxtCalUno.getText()));
        Materia tic = new Materia();
        tic.setNombre("Tecnología de información de colaboración");
        tic.setNota(Integer.parseInt(this.TxtTIC.getText()));
        Materia teologia = new Materia();
        teologia.setNombre("Teflexión Teológica");
        teologia.setNota(Integer.parseInt(this.TxtTeologia.getText()));
        cuarto.add(calculouno);
        cuarto.add(tic);
        cuarto.add(teologia);
        //AGREGANDO LOS DATOS DE LAS NOTAS DE 4TO AÑO AL ESTUDIANTE
        alumno.setPrimero(cuarto);
        LstModelo2.clear();
        LstModelo2.addElement(cuarto);
        this.LstNtCrtAn.setModel(LstModelo2);
        
        //CREANDO EL ARREGLO DE LAS NOTAS DE 5TO AÑO DEL ESTUDIANTE
        ArrayList<Materia> quinto = new ArrayList();
        Materia calculodos = new Materia();
        calculodos.setNombre("Cálculo 2");
        calculodos.setNota(Integer.parseInt(this.TxtCalDos.getText()));
        Materia poo = new Materia();
        poo.setNombre("programación Orientada a Objetos");
        poo.setNota(Integer.parseInt(this.TxtPOO.getText()));
        Materia dbd = new Materia();
        dbd.setNombre("Historia");
        dbd.setNota(Integer.parseInt(this.TxtDBD.getText()));
        quinto.add(calculodos);
        quinto.add(poo);
        quinto.add(dbd);
        //AGREGANDO LOS DATOS DE LAS NOTAS DE 5TO AÑO AL ESTUDIANTE
        alumno.setSegundo(quinto);
        LstModelo2.clear();
        LstModelo2.addElement(quinto);
        this.LstQntAn.setModel(LstModelo2);
        
        
        JOptionPane.showMessageDialog(null, alumno.toString());
    }//GEN-LAST:event_BtnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JCheckBox ChkBxFem;
    private javax.swing.JCheckBox ChkBxMasculino;
    private javax.swing.JCheckBox ChkBxOtro;
    private javax.swing.JComboBox<String> CmbCarrera;
    private javax.swing.JComboBox<String> CmbUni;
    private javax.swing.JLabel LblCalDos;
    private javax.swing.JLabel LblCalDos1;
    private javax.swing.JLabel LblCalUno;
    private javax.swing.JLabel LblCalUno1;
    private javax.swing.JLabel LblCarrera;
    private javax.swing.JLabel LblCedula;
    private javax.swing.JLabel LblDesBD;
    private javax.swing.JLabel LblDesBD1;
    private javax.swing.JLabel LblMstMatEv;
    private javax.swing.JLabel LblMstMatEv1;
    private javax.swing.JLabel LblMstNtCrt;
    private javax.swing.JLabel LblMstNtCrt1;
    private javax.swing.JLabel LblMstNtQnt;
    private javax.swing.JLabel LblMstNtQnt1;
    private javax.swing.JLabel LblNombreAlum;
    private javax.swing.JLabel LblNotasCrtAno;
    private javax.swing.JLabel LblNotasCrtAno2;
    private javax.swing.JLabel LblNotasQntAno;
    private javax.swing.JLabel LblNotasQntAno1;
    private javax.swing.JLabel LblPOO;
    private javax.swing.JLabel LblPOO1;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel LblTIC;
    private javax.swing.JLabel LblTIC1;
    private javax.swing.JLabel LblTolg;
    private javax.swing.JLabel LblTolg1;
    private javax.swing.JLabel LblUni;
    private javax.swing.JList<String> LstMatEv;
    private javax.swing.JList<String> LstMatEvl;
    private javax.swing.JList<String> LstNtCrtAn;
    private javax.swing.JList<String> LstNtCrtAno;
    private javax.swing.JList<String> LstQnt;
    private javax.swing.JList<String> LstQntAn;
    private javax.swing.JTextArea TxtAreaNombreAlum;
    private javax.swing.JTextField TxtCalDos;
    private javax.swing.JTextField TxtCalUno;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtDBD;
    private javax.swing.JTextField TxtPOO;
    private javax.swing.JTextField TxtTIC;
    private javax.swing.JTextField TxtTeologia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
